#服务相关配置
server: 
#HTTP端口
  port: 8088
  session:  
    #session超时时间，单位秒
    timeout:  600     
      
spring:
  #集群session存储方式
  session:  
    store-type: none   
  #数据源
  datasource: 
    url:  jdbc:mysql://rm-uf6bdv92a95017474oo.mysql.rds.aliyuncs.com:3306/phweb_dev?useUnicode=true&amp;characterEncoding=utf-8
    username:  puhao
    password:  Puhao2018
    driverClassName:  com.mysql.jdbc.Driver
    tomcat:
      #初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
#jpa相关配置
  jpa:  
  #是否自动生成/修改数据库表
    show-sql: true
    generate-ddl: false

#浏览器环境配置项，参见BrowserProperties
vinann:
  security: 
    browser:
      signInPage: /login.html
      signInResponseType: JSON
      singInSuccessUrl: /
      #rememberMeSeconds: 294000
      signOutUrl: /login.html
      #signUpUrl: /register.html

#session管理相关配置，参见SessionProperties
      session:  
        maximumSessions: 1
        maxSessionsPreventsLogin: false
        sessionInvalidUrl: /login.html

#图片验证码配置项，参见ImageCodeProperties
#vinann.security.code.image.length = 4
#vinann.security.code.image.width = 100
#vinann.security.code.image.height = 30
#vinann.security.code.image.expireIn = 30
#    code: 
#      image:  
#        url: /code/sms

#短信验证码配置项，参见SmsCodeProperties
#vinann.security.code.sms.length = 6
#vinann.security.code.sms.expireIn = 60
#      sms:  
#        url: /user/regist

#社交登录功能拦截的url,参见SocialProperties
#vinann.security.social.filterProcessesUrl = /qqLogin

#QQ登录配置，参见QQProperties
#vinann.security.social.qq.app-id = 101496570
#vinann.security.social.qq.app-secret = 8bb3dceb6deee36c9cf94f8450f45d1a
#vinann.security.social.qq.providerId = qq

#微信登录配置，参见WeixinProperties
#vinann.security.social.weixin.app-id = wxd99431bbff8305a0
#vinann.security.social.weixin.app-secret = 60f78681d063590a469f1b297feff3c4
#vinann.security.social.weixin.providerId = weixin

#认证服务器注册的第三方应用配置项，参见OAuth2ClientProperties
#vinann.security.oauth2.clients[0].clientId = vinann
#vinann.security.oauth2.clients[0].clientSecret = vinannsecret
#vinann.security.oauth2.clients[0].accessTokenValidateSeconds = 3600
#vinann.security.oauth2.clients[1].clientId = test
#vinann.security.oauth2.clients[1].clientSecret = test

#OAuth2认证服务器的tokenStore的类型，可选值为redis和jwt，值为jwt时发出的token为jwt
#vinann.security.oauth2.tokenStore = redis
#使用jwt时为token签名的秘钥
#vinann.security.oauth2.jwtSigningKey = vinann
#https://github.com/jojozhai/security
    