debug: true
is-prd: false
#服务相关配置
server: 
#HTTP端口
  port: 8088
  # 限制大小为5MB
  max-http-header-size: 5000000
  session:  
    #session超时时间，单位秒
    timeout:  28800
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  #集群session存储方式
  session:  
    store-type: none   
  #数据源
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    url:  jdbc:mysql://rm-uf6bdv92a95017474oo.mysql.rds.aliyuncs.com:3306/phweb_dev?useUnicode=true&amp;characterEncoding=utf-8
    username:  puhao
    password:  Puhao2018
    driverClassName:  com.mysql.jdbc.Driver
    #下面为连接池的补充设置，应用到上面所有数据源中
    #初始化大小，最小，最大
    initialSize:  5
    minIdle:  5
    maxActive:  20
    #配置获取连接等待超时的时间
    maxWait:  60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis:  60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #校验SQL，Oracle配置     validationQuery:  SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    validationQuery:  SELECT 'x'
    testWhileIdle:  true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize:  20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters:  stat,wall,slf4j
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat:  true
  boot:
    admin:
      client:
        url: 'http://127.0.0.1:8888'
#jpa相关配置
  jpa:  
  #是否自动生成/修改数据库表
    show-sql: true
    generate-ddl: false
  http:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
ph: 
  default:  
    #默认密码
    pwd: 123456
  file: 
    path: D:/workspace/hades/src/main/resources/static
    server: http://127.0.0.1:8088
  url: lan
qiniu:
  url: http://qiniu.offway.cn
  access-key: WU33Cpp1WJZAf4oIIHknc2ga3ZhQpgJo3UL-JUdB
  secret-key: ALb95JFSVi3mvSScoQa564HzDby_y2EasUhhmniV
  bucket: offwaypro
#极光推送
jpush:
  apns-production: false
  app-key: 23f3d1476579eda19a0da872
  master-secret: 90f4a69575d4a51c877f5dad
#美洽客服配置
meqia:  
  key:  $2a$12$DH0LKaxq.alh49rSMkOP0eaEfZzcwUb95Wg6cY5DTLRvI.CG6vZNi
#浏览器环境配置项，参见BrowserProperties
vinann:
  security: 
    browser:
      signInPage: /login.html
      signInResponseType: JSON
      singInSuccessUrl: /
      #rememberMeSeconds: 294000
      signOutUrl: /login.html
      #signUpUrl: /register.html

#session管理相关配置，参见SessionProperties
      session:  
        maximumSessions: 1
        maxSessionsPreventsLogin: false
        sessionInvalidUrl: /login.html
alipay:
  appid:  2019032863746574
  privatekey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCCnPID+2SZzACH8sSpH9lvqpDsLRBs32JkcRa4D1Zi7k6DVOTCpVljkCDMdKsw3rJLGLyjeAeEEBkRrZ10X3wAk9Acd0iY7EbmDZJ9sc5BhfFJwHul8ap+NZK9Fq5S/mHfUeQffVZwJ3bwbYZPTy3NXLEQKnWM/ARpVlWkOjk4a1dHZluF88yO6d53A3jZ0OOZbbVSazlnO5lv2zxA1dvTUYlYJDFpZBecpa2wpiPfTpsM6ywPLqHhqDaObu5o9uPCrbw64MlLCJAoeysOkfV+wFnZLuI6U6ItBYUDzk2Ge0bDRWYx3a5E9EJfvnZ92h5tVwCqF9TKi0lq4pbhJEMPAgMBAAECggEAUWH/PlHuzhGZpxuyQ/sPXY+2uyIdIOlTgmggktEjr4LzMsu7ujiS6QGOHjb3z/yCtV4Vc/m/HR92r1gxSqiQOD/hpUsB1h8q0f9U7rLSZGtT+/NOWAirhfZVlzJBrn7IdwCslp5fNISyjH6B+HrKfDIsNXlvQ0hoa0YbGLganTcDf9GjMSlhe7V/0ujx6gU2OuwZb+BsKu+Tx7LWwAkhADs+cob+X01I4cgfBxuJk9AM9VDmQ803GQo8fhCjWm4kuK4mhlRPiZqKxDIvdSRR6ECz1tgR7SzXsYpmteM+0yBqS47qfj+iKJ857NAW0knZrRSsXQgNjRmZdJtojnuHwQKBgQDj56QFTaySG+5s6bpA6KsB5bZBo3af6aJ2bphi8ZeNl7QtzXNPYcm3KsZeJDb3ZDC8ygqyKjzbVR6TXvtCbK27Jc/Mr4oxMk9oDsr8ZvIhLnQZktSvPg1aih1tfEGZxERioAMnTqjWy9M09vfV/euo4ovIg3ijXhFdiIlAf8VHbwKBgQCStuln7NT4JwtYUoVHJRSnCnkaZgpCV1ba4Hg9gOu1pW4Irx/XRrqkjvrYkLZpcJShz91AC2148rQeuRVjQcHWprdvicQHZ9IGIsXBqfOae81DUXSeZJgmNPoOw3BcejsR7Xl9Kf8k3sl05l2FXu7N3k8bRu/F2C9tmPUEizXuYQKBgElzpLdY21+TxPoxMigtVMAdyunIxziu0f+dkVuCRbgKxrVkW9+fwqVYEerRfS2qitKtw1i8qDSAcIRKvmwgHrYMb7amdMF6V4FQEzfZ7funvx9m5Uk9lIwzq1xYCcSHLwsiSyHmBiCEPKP7XNEJL2SU7zxGsyDj9nDQynuRMoHdAoGAfFZBps6iio/kYHzG8M1vHEWW7pVtul10gVhc7pq0qCPEBd4MmRAbG10FH8Y8oU1E2YFlG2LT6v2dQrBOfOj8kqKFsSRLGo+VAZg0inUyu0iSY6vDrnzIKREanqppLiZ0qzPbkwSlc6TPjJ+ywFX9AkGWPyK2D7CwOSy48ZndIeECgYBc1XtQ/h1Pqy/FmvpqZE9UshY4+YIIbJZcvmoGLjUGVb6qBGJz2BgIe+7jVPpWkwkwKQXFaMGCZZGKBpOuifEPTeWkpC+e3dHsxdZMY3JDL7ZppB8ppiGywGFQZvaJ2bmcNcUgXt4TRF65Y9YvNyzSUycFUg5Ajr22dgTtUs1bIw==
  publickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnzzD10iXx/jzFGqPWFrvSrsbvMk173bKnkxofqrtvh/e1MsUuSRBt4xNj1mxmZFeQuRgaZo6PgcqrRb1ImyOTqzQiTWYUAjBfRFTL9YmvVrefohnvwfGuTwIkkaMB/y9gG0rzhoVfFREWVTlQ4aXDWwtKMh4Ve497lCnxuesnBCD7Z0qCqmycqineiEspE9+f/hjDSMJYQdaChvOn/5GhzkXHrAKEpGrr68tB53LhGwIfYQsChZZLd3HkPlCAXSoJSDufNhSqrpn4UJ7B4gikQul7FA+kvJO4SdQN3EwaLHohT6pezFNOj6It2f47bRupgCWTsw4ORzcHnofNdEE/wIDAQAB
#图片验证码配置项，参见ImageCodeProperties
#vinann.security.code.image.length = 4
#vinann.security.code.image.width = 100
#vinann.security.code.image.height = 30
#vinann.security.code.image.expireIn = 30
#    code: 
#      image:  
#        url: /code/sms

#短信验证码配置项，参见SmsCodeProperties
#vinann.security.code.sms.length = 6
#vinann.security.code.sms.expireIn = 60
#      sms:  
#        url: /user/regist

#社交登录功能拦截的url,参见SocialProperties
#vinann.security.social.filterProcessesUrl = /qqLogin

#QQ登录配置，参见QQProperties
#vinann.security.social.qq.app-id = 101496570
#vinann.security.social.qq.app-secret = 8bb3dceb6deee36c9cf94f8450f45d1a
#vinann.security.social.qq.providerId = qq

#微信登录配置，参见WeixinProperties
#vinann.security.social.weixin.app-id = wxd99431bbff8305a0
#vinann.security.social.weixin.app-secret = 60f78681d063590a469f1b297feff3c4
#vinann.security.social.weixin.providerId = weixin

#认证服务器注册的第三方应用配置项，参见OAuth2ClientProperties
#vinann.security.oauth2.clients[0].clientId = vinann
#vinann.security.oauth2.clients[0].clientSecret = vinannsecret
#vinann.security.oauth2.clients[0].accessTokenValidateSeconds = 3600
#vinann.security.oauth2.clients[1].clientId = test
#vinann.security.oauth2.clients[1].clientSecret = test

#OAuth2认证服务器的tokenStore的类型，可选值为redis和jwt，值为jwt时发出的token为jwt
#vinann.security.oauth2.tokenStore = redis
#使用jwt时为token签名的秘钥
#vinann.security.oauth2.jwtSigningKey = vinann
#https://github.com/jojozhai/security
    